### PR TITLE
create FeatureFile and StepDefinition Class

### PR DESCRIPTION
**Pull request by Emmanuelduvalsaint**
Please review

### CODE REVIEW

**Review by nail-92 — CHANGES_REQUESTED** [review]
I would recommend to finish the US before creating pull request

**Review by McGeenie — APPROVED** [review]

**Review by ksafa74 — APPROVED** [review]

**Review by Emmanuelduvalsaint — COMMENTED** [review]
Thanks

**Comment by Emmanuelduvalsaint** [comment]
ok

**Review by McGeenie — APPROVED** [review]

**Review by ksafa74 — APPROVED** [review]
looks good. 👍

**Review by ksafa74 — APPROVED** [review]

**Review by ksafa74 — APPROVED** [review]

**Review by nail-92 — APPROVED** [review]

**Pull request merged**
